/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSaldoInicialRouteImport } from './routes/_authenticated/saldo-inicial'
import { Route as AuthenticatedImportacoesRouteImport } from './routes/_authenticated/importacoes'
import { Route as AuthenticatedFechamentoRouteImport } from './routes/_authenticated/fechamento'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedLancamentosIndexRouteImport } from './routes/_authenticated/lancamentos.index'
import { Route as AuthenticatedColaboradoresIndexRouteImport } from './routes/_authenticated/colaboradores.index'
import { Route as AuthenticatedLancamentosNovoRouteImport } from './routes/_authenticated/lancamentos.novo'
import { Route as AuthenticatedColaboradoresIdRouteImport } from './routes/_authenticated/colaboradores.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaldoInicialRoute =
  AuthenticatedSaldoInicialRouteImport.update({
    id: '/saldo-inicial',
    path: '/saldo-inicial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportacoesRoute =
  AuthenticatedImportacoesRouteImport.update({
    id: '/importacoes',
    path: '/importacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFechamentoRoute = AuthenticatedFechamentoRouteImport.update({
  id: '/fechamento',
  path: '/fechamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLancamentosIndexRoute =
  AuthenticatedLancamentosIndexRouteImport.update({
    id: '/lancamentos/',
    path: '/lancamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColaboradoresIndexRoute =
  AuthenticatedColaboradoresIndexRouteImport.update({
    id: '/colaboradores/',
    path: '/colaboradores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLancamentosNovoRoute =
  AuthenticatedLancamentosNovoRouteImport.update({
    id: '/lancamentos/novo',
    path: '/lancamentos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColaboradoresIdRoute =
  AuthenticatedColaboradoresIdRouteImport.update({
    id: '/colaboradores/$id',
    path: '/colaboradores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/fechamento': typeof AuthenticatedFechamentoRoute
  '/importacoes': typeof AuthenticatedImportacoesRoute
  '/saldo-inicial': typeof AuthenticatedSaldoInicialRoute
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/lancamentos/novo': typeof AuthenticatedLancamentosNovoRoute
  '/colaboradores/': typeof AuthenticatedColaboradoresIndexRoute
  '/lancamentos/': typeof AuthenticatedLancamentosIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/fechamento': typeof AuthenticatedFechamentoRoute
  '/importacoes': typeof AuthenticatedImportacoesRoute
  '/saldo-inicial': typeof AuthenticatedSaldoInicialRoute
  '/': typeof AuthenticatedIndexRoute
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/lancamentos/novo': typeof AuthenticatedLancamentosNovoRoute
  '/colaboradores': typeof AuthenticatedColaboradoresIndexRoute
  '/lancamentos': typeof AuthenticatedLancamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/fechamento': typeof AuthenticatedFechamentoRoute
  '/_authenticated/importacoes': typeof AuthenticatedImportacoesRoute
  '/_authenticated/saldo-inicial': typeof AuthenticatedSaldoInicialRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/_authenticated/lancamentos/novo': typeof AuthenticatedLancamentosNovoRoute
  '/_authenticated/colaboradores/': typeof AuthenticatedColaboradoresIndexRoute
  '/_authenticated/lancamentos/': typeof AuthenticatedLancamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/fechamento'
    | '/importacoes'
    | '/saldo-inicial'
    | '/colaboradores/$id'
    | '/lancamentos/novo'
    | '/colaboradores/'
    | '/lancamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/configuracoes'
    | '/fechamento'
    | '/importacoes'
    | '/saldo-inicial'
    | '/'
    | '/colaboradores/$id'
    | '/lancamentos/novo'
    | '/colaboradores'
    | '/lancamentos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/configuracoes'
    | '/_authenticated/fechamento'
    | '/_authenticated/importacoes'
    | '/_authenticated/saldo-inicial'
    | '/_authenticated/'
    | '/_authenticated/colaboradores/$id'
    | '/_authenticated/lancamentos/novo'
    | '/_authenticated/colaboradores/'
    | '/_authenticated/lancamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saldo-inicial': {
      id: '/_authenticated/saldo-inicial'
      path: '/saldo-inicial'
      fullPath: '/saldo-inicial'
      preLoaderRoute: typeof AuthenticatedSaldoInicialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importacoes': {
      id: '/_authenticated/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof AuthenticatedImportacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fechamento': {
      id: '/_authenticated/fechamento'
      path: '/fechamento'
      fullPath: '/fechamento'
      preLoaderRoute: typeof AuthenticatedFechamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos/': {
      id: '/_authenticated/lancamentos/'
      path: '/lancamentos'
      fullPath: '/lancamentos/'
      preLoaderRoute: typeof AuthenticatedLancamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores/': {
      id: '/_authenticated/colaboradores/'
      path: '/colaboradores'
      fullPath: '/colaboradores/'
      preLoaderRoute: typeof AuthenticatedColaboradoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos/novo': {
      id: '/_authenticated/lancamentos/novo'
      path: '/lancamentos/novo'
      fullPath: '/lancamentos/novo'
      preLoaderRoute: typeof AuthenticatedLancamentosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores/$id': {
      id: '/_authenticated/colaboradores/$id'
      path: '/colaboradores/$id'
      fullPath: '/colaboradores/$id'
      preLoaderRoute: typeof AuthenticatedColaboradoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedFechamentoRoute: typeof AuthenticatedFechamentoRoute
  AuthenticatedImportacoesRoute: typeof AuthenticatedImportacoesRoute
  AuthenticatedSaldoInicialRoute: typeof AuthenticatedSaldoInicialRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedColaboradoresIdRoute: typeof AuthenticatedColaboradoresIdRoute
  AuthenticatedLancamentosNovoRoute: typeof AuthenticatedLancamentosNovoRoute
  AuthenticatedColaboradoresIndexRoute: typeof AuthenticatedColaboradoresIndexRoute
  AuthenticatedLancamentosIndexRoute: typeof AuthenticatedLancamentosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedFechamentoRoute: AuthenticatedFechamentoRoute,
  AuthenticatedImportacoesRoute: AuthenticatedImportacoesRoute,
  AuthenticatedSaldoInicialRoute: AuthenticatedSaldoInicialRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedColaboradoresIdRoute: AuthenticatedColaboradoresIdRoute,
  AuthenticatedLancamentosNovoRoute: AuthenticatedLancamentosNovoRoute,
  AuthenticatedColaboradoresIndexRoute: AuthenticatedColaboradoresIndexRoute,
  AuthenticatedLancamentosIndexRoute: AuthenticatedLancamentosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
